name             'phpunit36'
maintainer       'Hisashi KOMINE'
maintainer_email 'hssh@hssh.jp'
license          'mit'
description      'Installs/Configures phpunit36'
long_description 'Installs/Configures phpunit36'
version          '0.1.0'
supports         'centos', '7.0'
